#!/bin/bash

mkdir -p data data/dram data/spikes data/delay

python data/script_generator.py \
           --neurons=$1 --timestep=5 \
           --chip=8 --core=8 --propagator=4 --dram_size=$2 \
           --spike_rate=10 --sparsity=0.002

cp simspec/neurosim0.simspec simspec/neurosim.simspec
cat simspec/neurosim.simspec

# bin/script_gen 16384 555000000
