#!/bin/bash
python data/script_generator.py \
           --neurons=16 --timestep=5 \
           --chip=1 --core=1 --propagator=1 --dram_size=256 \
           --spike_rate=1000 --sparsity=0.5 --delay=4

rm simspec/neurosim.simspec
cd simspec
ln -s neurosim0.simspec neurosim.simspec
cd ..
