#!/bin/bash

ID=$1
DIR=$(find workloads/microbench -name "$ID*")
DIR=${DIR##*/}
TIMESTEP=$(awk '/max_timestep/ {print $2}' workloads/microbench/$DIR/neurosim/simspec/neurosim.simspec)

./neurosim-tsim workloads/microbench/$DIR/neurosim/simspec/neurosim.simspec -o reports/${DIR}_${TIMESTEP}ts.rep
